export const jwtConstants = {
  secretAccess:
    'DO NOT USE THIS ACCESS. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
  secretRefresh:
    'DO NOT USE THIS REFRESH. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};
